export const STORAGE_KEYS = {
  LANGUAGE: 'LANGUAGE_KEY',
  COLOR_SCHEME: 'COLOR_SCHEME_KEY',
  AUTH_STORAGE: 'AUTH_STORAGE_KEY',
  REFRESH_TOKEN: 'REFRESH_TOKEN',
  PROFILE_STORAGE: 'PROFILE_STORAGE_KEY',
};
