const PROFILE_QUERY_KEYS = {
  HEADER: 'PROFILE_HEADER',
  GET_PROFILE_DETAILS: 'GET_PROFILE_DETAILS',
  UPDATE_BANNER: 'UPDATE_BANNER',
  EDIT_KUNYA: 'EDIT_KUNYA',
  DELETE_KUNYA: 'DELETE_KUNYA',
  GET_ADDRESSES: 'GET_ADDRESSES',
  ADDRESS_START: 'ADDRESS_START',
  GET_QUALIFICATIONS: 'GET_QUALIFICATIONS',
  // Add other profile-related query keys here
} as const;

export default PROFILE_QUERY_KEYS;
